apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-tuji
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-tuji
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-tuji
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-tuji
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-tuji
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iaqp-tenant/rhtap-demo-app/hacbs-test-project-tuji@sha256:0c7cba3933de17fdff4c567d7141f7864626ff6d0eda5285b7eec5a123b13864
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
