apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tuji
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iaqp-tenant/rhtap-demo-app/hacbs-test-project-tuji@sha256:0c7cba3933de17fdff4c567d7141f7864626ff6d0eda5285b7eec5a123b13864
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
