apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tuji
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iaqp-tenant/rhtap-demo-app/hacbs-test-project-tuji@sha256:640fe3dc17a68d7573f2b990f0f4aa4196a64b9b4af651aa775c7ae92d1eb0a8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
